### ISSUE TITLE
Scanner fails with "Error: return #17000 is missing call #95"

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1258]
Seen when running Analysis in GitHub Actions:

```Error: Error processing "tmp/appmap/rspec/OpenApiSpecification_DocsController_json_returns_the_Open_API_Swagger_json_file.appmap.json"
    at /home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/scanner/built/cli/scan.js:89:29
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/scanner/built/cli/scan.js:5:58) {
  [cause]: Error: return #17000 is missing call #95
      at H.add (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:8115)
      at Q.add (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:8525)
      at /home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:9705
      at Array.forEach (<anonymous>)
      at Ee.source (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:9556)
      at new Ee (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:9316)
      at B (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/models/dist/index.cjs:3:12413)
      at /home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/scanner/built/cli/scan.js:75:57
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/.npm/_npx/5eabe842035cb8e3/node_modules/@appland/scanner/built/cli/scan.js:5:58)
}
```

Same user also encountered the issue with a slightly different stack:

```Error: return #17000 is missing call #95
    at H.add (/snapshot/appmap-js/packages/models/dist/index.cjs:3:8115)
    at Q.add (/snapshot/appmap-js/packages/models/dist/index.cjs:3:8525)
    at /snapshot/appmap-js/packages/models/dist/index.cjs:3:9705
    at Array.forEach (<anonymous>)
    at Ee.source (/snapshot/appmap-js/packages/models/dist/index.cjs:3:9556)
    at parseHTTPServerRequests (/snapshot/appmap-js/packages/openapi/dist/parseHTTPServerRequests.js:5:48)
    at OpenAPICommand.collectAppMap (/snapshot/appmap-js/packages/cli/built/cmds/openapi.js:84:51)
```

**Comment by kgilpin** [comment]
Worthy of note, the appmap-ruby agent was recording tests and requests at
the same time. Is this related?

User was using the following idiom in the Gemfile:

gem 'appmap' if ENV['APPMAP'] == 'true'

Is this related?

Is there a different way that we want to support conditional loading or
activation of the appmap agent? We implement recording by default to
maximize the chances of a user getting an appmap during onboarding. But
once that's happened, the user may want a way to enable/disable the appmap
agent via env var.

If a user sets APPMAP=true in order to trigger the gem loading (as above),
*all recording* will be enabled, per the docs -
https://appmap.io/docs/reference/appmap-ruby.html#advanced-runtime-options

Maybe we want a different env var that will activate the gem without also
activating all recording.

**Comment by kgilpin** [comment]
The user had `APPMAP=true` in their environment (triggering both request and test recording at the same time), and may also have had some very non-standard test code. 

This is worth looking into, but isn't as urgent as some other issues.

**Comment by kgilpin** [comment]
Also, the root cause is probably in appmap-ruby.
