### ISSUE TITLE
A helpful error message is returned when invalid files are passed to sequence-diagram-diff

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1344]
A user attempts to diff two AppMaps, e.g.:
```
$ npx @appland/appmap@latest sequence-diagram-diff base.appmap.json head.appmap.json
```
A stacktrace is reported instead of a clear error message:
```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at unparseDiagram (/Users/brikelly/.npm/_npx/93d874c56accaa6c/node_modules/@appland/sequence-diagram/dist/unparseDiagram.js:7:20)
    at readDiagramFile (/Users/brikelly/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/cmds/sequenceDiagram/readDiagramFile.js:8:50)
    at async compareFiles (/Users/brikelly/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/cmds/sequenceDiagramDiff.js:75:29)
    at async Object.handler (/Users/brikelly/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/cmds/sequenceDiagramDiff.js:131:9)
```
The desired behavior is that the user get a more helpful error message indicating that they should pass diagram files instead of AppMap files. Specifically, if we know that both files passed were both AppMap format, we should suggest they run the following commands to generate diagram files for each and then re-run the original command with the new diagrams:
```
appmap sequence-diagram -f json base.appmap.json
appmap sequence-diagram -f json head.appmap.json
appmap sequence-diagram-diff base.sequence.json head.sequence.json
```

This zip contains 2 AppMaps which can be used to test the current behavior, and to create diagram files if needed. [2-appmaps.zip](https://github.com/getappmap/appmap-js/files/12502764/2-appmaps.zip)

**Comment by Parthfaladu** [comment]
@brikelly i am starting work to set helpful error message on AppMap files upload
