### ISSUE TITLE
RPC exception: "unrecognized field 'appmap'"

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1549]
When prompted with the question `how can i install appmap ruby`. I could not replicate this again after a reload. I've attached the AppMaps included in the search.

[minitest.zip](https://github.com/getappmap/appmap-js/files/13979114/minitest.zip)

```
127575 [Stdout] Available JSON-RPC methods: appmap.data, appmap.filter, appmap.metadata, appmap.sequenceDiagram, explain, explain.status, index.numProcessed, search
127575 [Stdout] Running JSON-RPC server on port: 38631
127575 [Stderr] Handling exception: Error
127575 [Stderr]     at /home/db/.config/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:2982:34
127575 [Stderr]     at Object.<anonymous> (/home/db/.config/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:3475:3)
127575 [Stderr]     at Module._compile (node:internal/modules/cjs/loader:1316:14)
127575 [Stderr]     at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
127575 [Stderr]     at Module.load (node:internal/modules/cjs/loader:1171:32)
127575 [Stderr]     at Module._load (node:internal/modules/cjs/loader:1012:12)
127575 [Stderr]     at f._load (node:electron/js2c/asar_bundle:2:13377)
127575 [Stderr]     at Module.require (node:internal/modules/cjs/loader:1195:19)
127575 [Stderr]     at require (node:internal/modules/cjs/helpers:110:18)
127575 [Stderr]     at Object.<anonymous> (/home/db/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/FindAppMaps.js:11:32) {
127575 [Stderr]   name: 'QueryParseError',
127575 [Stderr]   message: "unrecognised field 'appmap', possible fields: 'name', 'source_location', 'code_objects', 'queries', 'routes', 'external_routes', 'parameters'",
127575 [Stderr]   start: 20,
127575 [Stderr]   end: 26
127575 [Stderr] }
```

**Comment by kgilpin** [comment]
We don't use lunr for this any more.
