### ISSUE TITLE
Unrecognized field in search

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1592]
```
3546 [Stderr] Handling exception: Error
3546 [Stderr]     at /Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:2982:34
3546 [Stderr]     at Object.<anonymous> (/Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:3475:3)
3546 [Stderr]     at Module._compile (node:internal/modules/cjs/loader:1316:14)
3546 [Stderr]     at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
3546 [Stderr]     at Module.load (node:internal/modules/cjs/loader:1171:32)
3546 [Stderr]     at Module._load (node:internal/modules/cjs/loader:1012:12)
3546 [Stderr]     at f._load (node:electron/js2c/asar_bundle:2:13377)
3546 [Stderr]     at Module.require (node:internal/modules/cjs/loader:1195:19)
3546 [Stderr]     at require (node:internal/modules/cjs/helpers:110:18)
3546 [Stderr]     at Object.<anonymous> (/Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/AppMapIndex.js:11:32) {
3546 [Stderr]   name: 'QueryParseError',
3546 [Stderr]   message: "unrecognised field 'dao', possible fields: 'name', 'source_location', 'code_objects', 'queries', 'routes', 'external_routes', 'parameters'",
3546 [Stderr]   start: 58,
3546 [Stderr]   end: 61
3546 [Stderr] }
3546 [Stderr] Stack trace: Error
3546 [Stderr]     at /Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:2982:34
3546 [Stderr]     at Object.<anonymous> (/Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/lunr/lunr.js:3475:3)
3546 [Stderr]     at Module._compile (node:internal/modules/cjs/loader:1316:14)
3546 [Stderr]     at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
3546 [Stderr]     at Module.load (node:internal/modules/cjs/loader:1171:32)
3546 [Stderr]     at Module._load (node:internal/modules/cjs/loader:1012:12)
3546 [Stderr]     at f._load (node:electron/js2c/asar_bundle:2:13377)
3546 [Stderr]     at Module.require (node:internal/modules/cjs/loader:1195:19)
3546 [Stderr]     at require (node:internal/modules/cjs/helpers:110:18)
3546 [Stderr]     at Object.<anonymous> (/Users/kgilpin/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/AppMapIndex.js:11:32)
```

**Comment by dustinbyrne** [comment]
With the following prompt I've gotten this error three out of five times:
```
write rspecs for Activation::Request
```

**Comment by kgilpin** [comment]
Ok let’s include this in an epic.

**Comment by dustinbyrne** [comment]
Fixed
