### ISSUE TITLE
Vector terms search error

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1621]
When vector terms is malformed, it can cause search errors in the backend. 

For example, the vector terms service may be improperly returning non-JSON. In that case, the user's raw question is emitted as the vector terms, resulting in terms such as:

```
36744ms [vectorTerms] summarize the functionality this typescript comment. emit comment only, surrounded backtick fences. export default async function buildcontext(searchresults: searchrpc.searchresult[]): promise<{ sequencediagrams: string[]; codesnippets: map<string, string>; codeobjects: set<string>; const sequencediagrams new array<string>(); codesnippets string>(); codeobjects set<string>(); buildsequencediagram (result: searchrpc.searchresult) result.events.map((event) event.fqid); appmapfilter appmapfilter(); appmapfilter.declutter.context.on true; appmapfilter.declutter.context.names codeobjects; filterstate serializefilter(appmapfilter); plantuml await sequencediagramhandler(result.appmap, filter: filterstate, format: 'plantuml', formatoptions: disablemarkup: true }); assert(typeof === 'string'); sequencediagrams.push(plantuml); examinedlocations for (const result searchresults) buildsequencediagram(result); event result.events) (!event.location) codeobjects.add(event.fqid); continue; (examinedlocations.has(event.location)) examinedlocations.add(event.location); (codesnippets.has(event.location)) snippets lookupsourcecode(event.location); (snippets) codesnippets.set(event.location, snippets.join('\n')); return sequencediagrams, codesnippets,
```

**Comment by kgilpin** [comment]
Another example: 

```
[AppMapIndex] Added 376 AppMaps to full-text index in 678ms
Error
    at /Users/kgilpin/source/appland/appmap-js/node_modules/lunr/lunr.js:2982:34
    at Object.<anonymous> (/Users/kgilpin/source/appland/appmap-js/node_modules/lunr/lunr.js:3475:3)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at Module.patchedRequire [as require] (/Users/kgilpin/source/appland/appmap-js/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/kgilpin/source/appland/appmap-js/packages/cli/built/fulltext/AppMapIndex.js:11:32) {
  name: 'QueryParseError',
  message: "unrecognised field 'terms', possible fields: 'name', 'source_location', 'code_objects', 'queries', 'routes', 'external_routes', 'parameters'",
  start: 69,
  end: 74
```

**Comment by kgilpin** [comment]
I think this will fix it:

```
          for (const term of obj.split(/[._-]/))
            terms.add(term.match(/[\p{Alphabetic}|\p{Number}]+/u)?.[0] || '');
```

**Comment by kgilpin** [comment]
https://github.com/getappmap/appmap-js/pull/1625/files#diff-ed1340dd37c21a403e8ae3d7ede6d2be54706344c315d0a55cf6871f0de5a6bdR86
