### ISSUE TITLE
Failed tests aren't reported when they are recorded by appmap-node

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1648]
Example: https://github.com/getappmap/appmap-js/actions/runs/8290941422/job/22689881296

```
Warning: Command "appmap compare-report --source-url https://github.com/getappmap/appmap-js/blob/7270903a8b12148bc4cd930668b40eb2bd0ace09 --appmap-url https://getappmap.com/github_artifact?owner=getappmap&repo=appmap-js&run_id=8290941422&base_revision=3d9f7a57b95fb92b51e21340ba9d6d8efd9c0dc3&head_revision=7270903a8b12148bc4cd930668b40eb2bd0ace09 .appmap/change-report/3d9f7a57b95fb92b51e21340ba9d6d8efd9c0dc3-7270903a8b12148bc4cd930668b40eb2bd0ace09" exited with failure code 1
Warning: TypeError: Cannot read properties of undefined (reading 'split')
    at source_url (/snapshot/appmap-js/packages/cli/built/report/urlHelpers.js)
    at TestFailure.source_link (/snapshot/appmap-js/packages/cli/built/report/urlHelpers.js)
    at TestFailure.wrapper (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:13:112)
    at prog (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at execIteration (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.wrapper (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:49)
    at Object.prog [as fn] (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
```

Seems like the change report requires source location to be present; however, this is not required by the spec.

**Comment by kgilpin** [comment]
Another reason that test failures aren't being reported is the absence of the `source_location` on appmap-node data.
