### ISSUE TITLE
Exception during full text search

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1767]
```
1798350 [Stderr] Explain received context request: search
1798350 [Stderr] Warning: No keywords provided, context result may be unpredictable
1798350 [Stdout] Wrote file index to /tmp/appmap-files-1714590495846y9ZQf0/index.sqlite
1798350 [Stderr] Explain context function searchContext threw an error:
1798350 [Stderr] SqliteError: fts5: syntax error near ""
1798350 [Stderr]     at FileIndex.search (/snapshot/appmap-js/packages/cli/built/fulltext/FileIndex.js)
1798350 [Stderr]     at /snapshot/appmap-js/packages/cli/built/rpc/explain/collectContext.js
1798350 [Stderr]     at withIndex (/snapshot/appmap-js/packages/cli/built/fulltext/withIndex.js)
1798350 [Stderr]     at async ContextCollector.collectContext (/snapshot/appmap-js/packages/cli/built/rpc/explain/collectContext.js)
1798350 [Stderr]     at async collectContext (/snapshot/appmap-js/packages/cli/built/rpc/explain/collectContext.js)
1798350 [Stderr]     at async Explain.searchContext (/snapshot/appmap-js/packages/cli/built/rpc/explain/explain.js)
1798350 [Stderr]     at async invokeContextFunction (/snapshot/appmap-js/packages/cli/built/rpc/explain/explain.js)
1798350 [Stderr]     at async Object.onRequestContext (/snapshot/appmap-js/packages/cli/built/rpc/explain/navie/navie-remote.js)
1798350 [Stderr]     at async AIClient.handleMessage (/snapshot/appmap-js/packages/client/dist/src/aiClient.js:64:33) {
1798350 [Stderr]   code: 'SQLITE_ERROR'
1798350 [Stderr] }
1798350 [Stderr] Handling exception: CodedError: Cannot convert undefined or null to object
1798350 [Stderr]     at Socket.<anonymous> (/snapshot/appmap-js/packages/client/dist/src/aiClient.js:23:38)
1798350 [Stderr]     at Socket.emitEvent (/snapshot/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:516:26)
1798350 [Stderr]     at Socket.onevent (/snapshot/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:506:18)
1798350 [Stderr]     at Socket.onpacket (/snapshot/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:474:22)
1798350 [Stderr]     at Manager.<anonymous> (/snapshot/appmap-js/node_modules/@socket.io/component-emitter/index.js:143:20)
1798350 [Stderr]     at /snapshot/appmap-js/node_modules/socket.io-client/build/cjs/manager.js:237:18
1798350 [Stderr]     at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
1798350 [Stderr]   code: 500
1798350 [Stderr] }
```

**Comment by dustinbyrne** [comment]
This seems to occur randomly, potentially related to LLM output? Running the same prompt again may not hit this exception.
```
Wrote file index to /tmp/appmap-files-1715785708637XXXXXXRFFbQz/index.sqlite
Explain context function searchContext threw an error:
SqliteError: fts5: syntax error near ""
    at FileIndex.search (/home/db/dev/applandinc/appmap-js/packages/cli/built/fulltext/FileIndex.js:76:51)
    at /home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/collectContext.js:134:184
    at withIndex (/home/db/dev/applandinc/appmap-js/packages/cli/built/fulltext/withIndex.js:24:22)
    at async ContextCollector.collectContext (/home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/collectContext.js:134:36)
    at async collectContext (/home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/collectContext.js:179:12)
    at async Explain.searchContext (/home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/explain.js:90:30)
    at async invokeContextFunction (/home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/explain.js:122:20)
    at async Object.onRequestContext (/home/db/dev/applandinc/appmap-js/packages/cli/built/rpc/explain/navie/navie-remote.js:41:44)
    at async AIClient.handleMessage (/home/db/dev/applandinc/appmap-js/packages/client/dist/src/aiClient.js:64:33) {
  code: 'SQLITE_ERROR'
}
Error handled by Explain: Error: Cannot convert undefined or null to object
Handling exception: CodedError: Cannot convert undefined or null to object
    at Socket.<anonymous> (/home/db/dev/applandinc/appmap-js/packages/client/dist/src/aiClient.js:23:38)
    at Socket.emitEvent (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:516:26)
    at Socket.onevent (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:506:18)
    at Socket.onpacket (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:474:22)
    at Emitter.emit (/home/db/dev/applandinc/appmap-js/node_modules/@socket.io/component-emitter/index.js:143:20)
    at /home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/manager.js:237:18
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 500
}
Stack trace: Error: Cannot convert undefined or null to object
    at Socket.<anonymous> (/home/db/dev/applandinc/appmap-js/packages/client/dist/src/aiClient.js:23:38)
    at Socket.emitEvent (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:516:26)
    at Socket.onevent (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:506:18)
    at Socket.onpacket (/home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/socket.js:474:22)
    at Emitter.emit (/home/db/dev/applandinc/appmap-js/node_modules/@socket.io/component-emitter/index.js:143:20)
    at /home/db/dev/applandinc/appmap-js/node_modules/socket.io-client/build/cjs/manager.js:237:18
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Error handled by Explain: [object Object]
Handling exception: { code: 500, message: 'Cannot convert undefined or null to object' }
```
