### ISSUE TITLE
Navie with Anyscale endpoints returns 'fastapi.exceptions.HTTPException: 400: Only one system message can be specified. 

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-js#1860]
When configuring Navie to use a remotely hosted Anyscale endpoint ([per the documentation](https://appmap.io/docs/reference/navie.html#anyscale-endpoints)).   Making any query to the endpoint with the Navie UI returns the following error. 

```
53043 [Stderr]   error: {
53043 [Stderr]     message: 'Only one system message can be specified. (Request ID: ec5ca433-4d1d-43f5-b22c-31402926edc9)',
53043 [Stderr]     internal_message: 'fastapi.exceptions.HTTPException: 400: Only one system message can be specified. (Request ID: ec5ca433-4d1d-43f5-b22c-31402926edc9)',
53043 [Stderr]     code: 400,
53043 [Stderr]     type: 'OpenAIHTTPException',
53043 [Stderr]     param: {}
53043 [Stderr]   },
53043 [Stderr]   code: 400,
53043 [Stderr]   param: {},
53043 [Stderr]   type: 'OpenAIHTTPException',
53043 [Stderr]   attemptNumber: 1,
53043 [Stderr]   retriesLeft: 6
53043 [Stderr] }
53043 [Stderr] Stack trace: Error: 400 Only one system message can be specified. (Request ID: ec5ca433-4d1d-43f5-b22c-31402926edc9)
53043 [Stderr]     at APIError.generate (/snapshot/appmap-js/node_modules/openai/error.js:44:20)
53043 [Stderr]     at OpenAI.makeStatusError (/snapshot/appmap-js/node_modules/openai/core.js:263:33)
53043 [Stderr]     at OpenAI.makeRequest (/snapshot/appmap-js/node_modules/openai/core.js:306:30)
53043 [Stderr]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
53043 [Stderr]     at async /snapshot/appmap-js/node_modules/@langchain/openai/dist/chat_models.cjs:654:29
53043 [Stderr]     at async RetryOperation._fn (/snapshot/appmap-js/node_modules/p-retry/index.js:50:12)
```

**Comment by kgilpin** [comment]
@dividedmind I seem to recall that the System messages were combined together into one? Maybe something has broken this, and we need an assertion in the test suite?

**Comment by dividedmind** [comment]
> @dividedmind I seem to recall that the System messages were combined together into one? Maybe something has broken this, and we need an assertion in the test suite?

The problem was that this was only applied for explain, and in #1804 assistant messages were mistakenly tagged "system". I'll fix both of these.
