### ISSUE TITLE
No context found when there is an untracked directory

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1888]
## Situtation

Repository contains an untracked directory.

Ask Navie a question.

## Observed behavior

Navie log:

```
Explain context function searchContext threw an error:
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
No context found
Handling exception: TypeError: context.some is not a function
    at ApplyContextService.addSystemPrompts (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/apply-context-service.js:61:44)
    at LookupContextService.applyContext (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/lookup-context-service.js:59:29)
    at ContextService.<anonymous> (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/context-service.js:34:50)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/context-service.js:5:58)
Stack trace: TypeError: context.some is not a function
    at ApplyContextService.addSystemPrompts (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/apply-context-service.js:61:44)
    at LookupContextService.applyContext (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/lookup-context-service.js:59:29)
    at ContextService.<anonymous> (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/context-service.js:34:50)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kgilpin/source/appland/appmap-js/packages/navie/dist/services/context-service.js:5:58)
```

**Comment by kgilpin** [comment]
Resolved via https://github.com/getappmap/appmap-js/pull/1892
