### ISSUE TITLE
Sonnet connection error is unhandled

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#2002]
https://github.com/getappmap/navie-benchmark/actions/runs/10941138268/job/30375466144#step:7:1372

```
Traceback (most recent call last):
 File "/home/sergey/dev/django/tests/expressions/tests.py", line 1218, in test_duration_expressions
	list(Experiment.objects.annotate(duration=F('estimated_time') + delta))
 File "/home/sergey/dev/django/django/db/models/query.py", line 269, in __iter__
	self._fetch_all()
 File "/home/sergey/dev/django/django/db/models/query.py", line 1172, in _fetch_all
	self._result_cache = list(self._iterabl... (1925)
4286ms [completion] claude-3-5-sonnet-20240620 0
Error: Failed to complete: Connection error.
    at AnthropicCompletionService.complete_1 (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:185:23)
    at complete_1.throw (<anonymous>)
    at resume (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:24:44)
    at reject (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:27:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Handling exception: Error: Failed to complete: Connection error.
    at AnthropicCompletionService.complete_1 (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:185:23)
    at complete_1.throw (<anonymous>)
    at resume (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:24:44)
    at reject (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:27:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Stack trace: Error: Failed to complete: Connection error.
    at AnthropicCompletionService.complete_1 (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:185:23)
    at complete_1.throw (<anonymous>)
    at resume (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:24:44)
    at reject (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:27:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dividedmind** [comment]
This uses old Navie version. It would be very helpful to know exactly what the error is by running Navie incorporating https://github.com/getappmap/appmap-js/pull/1992
