### ISSUE TITLE
Installer can't open pom.xml

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#755]
In a few projects we got the following install-agent:failure

```
Error: UNKNOWN: unknown error, open 'C:\Users\test\CRFAutomationGitLab\oneSite\pom.xml'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at EncodedFile.write (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\encodedFile.js:35:22)
    at MavenInstaller.installAgent (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\mavenInstaller.js:116:21)
    at AgentInstallerProcedure.run (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\agentInstallerProcedure.js:57:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _handler (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\install-agent.js:133:17)
    at async Object.handler (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\install-agent.js:222:35)
```

**Comment by symwell** [comment]
Since there error is on `EncodedFile.write`, I wonder if the error is that pom.xml couldn't be written.
