### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length') in validateProject

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#770]
Saw this error 
```
TypeError: Cannot read properties of undefined (reading 'length')
    at AgentInstallerProcedure.validateProject (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\agentProcedure.js:78:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AgentInstallerProcedure.run (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\agentInstallerProcedure.js:67:13)
    at async _handler (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\install-agent.js:133:17)
    at async Object.handler (C:\Users\test\AppData\Local\npm-cache\_npx\3007b677135bbf3c\node_modules\@appland\appmap\built\cmds\agentInstaller\install-agent.js:222:35)
```

Seems to be coming from validateProject from this line
```
    const errors = Array.isArray(validationResult) ? validationResult : validationResult.errors;
    if (errors.length > 0) {
```

**Comment by symwell** [comment]
To debug this I edited `~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/appmap-0.93.2/lib/appmap/command/agent_setup/validate.rb` so that instead of printing out a JSON verification output it prints invalid JSON, to trigger an error. Then called
```
~/src/appmap-js/packages/cli$ npm start install /home/test/src/sample_app_6th_ed
```

**Comment by dustinbyrne** [comment]
I was actually able to recreate this just now with the following steps:
```sh
$ mkdir js-project
$ cd js-project
$ yarn init
   (enter enter enter...)
$ yarn
$ npx @appland/appmap install
```

I received the following output from the install command:
```
Installing AppMap agent for ....
? AppMap is about to be installed. Confirm the details below.
  !!! Telemetry disabled !!!: true
  Project type: yarn
  Project directory: /home/db/dev/tmp/js-project
  Git remote: [git remote failed, fatal: not a git repository (or any of the parent directories): .git]

  Is this correct? Yes
? An appmap.yml configuration file already exists. How should the conflict be resolved? Use existing
✔ Installing AppMap...
⠙ Validating the AppMap agent...Cannot read properties of undefined (reading 'length')
✖ Validating the AppMap agent...
! Installation failed. View error details? Yes

TypeError: Cannot read properties of undefined (reading 'length')
    at AgentInstallerProcedure.validateProject (/home/db/.npm/_npx/505416/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/agentProcedure.js:78:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AgentInstallerProcedure.run (/home/db/.npm/_npx/505416/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/agentInstallerProcedure.js:67:13)
    at async _handler (/home/db/.npm/_npx/505416/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/install-agent.js:133:17)
    at async Object.handler (/home/db/.npm/_npx/505416/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/install-agent.js:222:35)
```

It looks like the issue is here:
https://github.com/getappmap/appmap-js/blob/main/packages/cli/src/cmds/agentInstaller/agentProcedure.ts#L83

**Comment by symwell** [comment]
```
Validating the AppMap agent...stdout is
{
  "filename": "appmap.yml",
  "configuration": {
    "contents": "name: js-project\npackages: []\n"
  }
}
errors are
undefined
```
