### ISSUE TITLE
Yarn workspaces are not detected as sub-projects

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#797]
Yarn packages must be detected as sub-projects otherwise `yarn` installation will fail.

```
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
```

**Comment by symwell** [comment]
Now sub-projects are detected and we get the following error.

Also referenced [here](https://github.com/getappmap/appmap-js/issues/905). Seems hard to [reconcile](https://github.com/getappmap/vscode-appland/pull/64) although there was some kind of [workaround](https://github.com/getappmap/appmap-agent-js/issues/167) for it in `appmap-agent-js`.
```
~/src/appmap-js/packages/cli$ npm start install -- -d /home/test/tmp/js-project2/

> @appland/appmap@3.59.1 start
> ts-node src/cli.ts install -d /home/test/tmp/js-project2/

? This directory contains sub-projects. Would you like to choose sub-projects for installation? Yes
? Select the projects to install AppMap to. dir_one
Installing AppMap agent for dir_one...
? AppMap is about to be installed. Confirm the details below.
  !!! Telemetry disabled !!!: true
  Project type: yarn
  Project directory: /home/test/tmp/js-project2/packages/dir_one
  Git remote: [git remote failed, fatal: not a git repository (or any of the parent directories): .git]

  Is this correct? Yes
⠏ Installing AppMap...An error occurred while running the command: npx @appland/appmap-agent-js init /home/test/tmp/js-project2/packages/dir_one
The command exited with code 1
>  /home/test/src/appmap-js/node_modules/npm/lib/utils/explain-dep.js:1
>  const chalk = require('chalk')
>                ^
>  
>  Error [ERR_REQUIRE_ESM]: require() of ES Module /home/test/src/appmap-js/node_modules/npm/node_modules/chalk/source/index.js from /home/test/src/appmap-js/node_modules/npm/lib/utils/explain-dep.js not supported.
>  Instead change the require of index.js in /home/test/src/appmap-js/node_modules/npm/lib/utils/explain-dep.js to a dynamic import() which is available in all CommonJS modules.
>      at Object.<anonymous> (/home/test/src/appmap-js/node_modules/npm/lib/utils/explain-dep.js:1:15)
>      at Object.<anonymous> (/home/test/src/appmap-js/node_modules/npm/lib/utils/explain-eresolve.js:5:49)
>      at Object.<anonymous> (/home/test/src/appmap-js/node_modules/npm/lib/utils/setup-log.js:10:21)
>      at Object.<anonymous> (/home/test/src/appmap-js/node_modules/npm/lib/npm.js:61:18)
>      at module.exports (/home/test/src/appmap-js/node_modules/npm/lib/cli.js:21:15)
>      at Object.<anonymous> (/home/test/src/appmap-js/node_modules/npm/bin/npx-cli.js:125:1) {
>    code: 'ERR_REQUIRE_ESM'
>  }
>  
>  Node.js v18.8.0
✖ Installing AppMap...
! Installation failed. View error details? Yes
```
