### ISSUE TITLE
Failure when loading test configuration

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#798]
```
TypeError: Cannot create property 'env' on string 'pytest .'
at areTestCasesConfigured (@appland/appmap/built/cmds/record/test/areTestCommandsConfigured.js:14:49)
at test (@appland/appmap/built/cmds/record/state/record_test.js:12:55)
at commandFn (@appland/appmap/built/cmds/record/record.js:87:38)
at async runCommand (@appland/appmap/built/cmds/runCommand.js:14:21)
```

**Comment by ahtrotta** [comment]
Is there a link to an Azure log?
