### ISSUE TITLE
ENOTDIR: not a directory, chdir

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#801]
Got [this](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-20T12%3A27%3A17.216Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-20T12%3A27%3A17.216Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%227ee9383e81c2dd97a6326950267f68918a59e50932018d55a60cbf275b62c7c2%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog) failure

```
Error: ENOTDIR: not a directory, chdir '/home/test/projects/hash' -> '/home/test/projects/hash/src/client/main.py'
    at process.wrappedChdir (internal/bootstrap/switches/does_own_process_state.js:116:14)
    at process.chdir (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/graceful-fs/polyfills.js:22:11)
    at commandFn (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/record/record.js:65:37)
    at runCommand (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/runCommand.js:14:27)
    at Object.handler (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/record/record.js:130:41)
    at /home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:8891
    at j (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:9502)
    at M.runCommand (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:7231)
```

It's not a directory, it's a symbolic link that points to a file.  It may be worth trying to reproduce this.

**Comment by dividedmind** [comment]
It's not a symbolic link, it straight up tried to chdir to `/home/test/projects/hash/src/client/main.py`. It's just a user error — they gave the binary path as the `directory` argument to the command: `appmap record test -d /home/mouhsenibrahim/projects/hash/src/client/main.py`. Thirty three seconds later they figured it out (`appmap record test -d /home/mouhsenibrahim/projects/hash/src/client`), as evidenced in [the rest of their session](https://portal.azure.com#@d03f5316-f32a-4633-a0ec-dc62399e533b/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA4WQMWvDMBCF9%252FwKoSkB20hnJFkBd0qGQMdOLaEo0qV1sSUjyW2H%252FvgqIaVbe8vB4927j7f4IXhil5TDtH9Hn9Pqi3y8YkSShwlTNtNM7nriTMaLsKbAAGrOamAPHLagtlw1wOUj3axIGePdLW5X7D6V%252BPREzTxPZm7sODQJ00U8OHokNvhsBp8IVYi67VrsuAXntDKyBakFA6nOstO8M0KjYLoFxjsnhJHMns6gxEmCVRZowcbPjN5dKcbwco%252B%252BTzmO6Nd%252F8hQrPW6qn7P%252Bf3N5NcfwhjbXEUN0GH%252B7qog3E1ZkSRifD666kVz3N%252FSPzOpsAQAA).
