### ISSUE TITLE
An empty test command can be run

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#802]
Unknown as to how this may occur. It's possible this empty value is loaded from configuration?

```sh
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
at new NodeError (node:internal/errors:387:5)
at normalizeSpawnArguments (node:child_process:531:11)
at spawn (node:child_process:726:13)
at Function.waitFor (@appland\appmap\built\cmds\record\testCaseRecording.js:104:52)
at testCasesRunning (@appland\appmap\built\cmds\record\state\testCasesRunning.js:9:39)
```

**Comment by symwell** [comment]
Reproduced by not accepting the suggested test command and instead providing a command that consists of one space character.
```
~/src/appmap-js/packages/cli$ npm start record test -- -d ~/src/sample_app_6th_ed/

> @appland/appmap@3.47.0 start
> ts-node src/cli.ts record test -d /home/test/src/sample_app_6th_ed/

The following test commands were provided by your AppMap configuration (appmap.yml):

APPMAP=true DISABLE_SPRING=true bundle exec rails test

? Use these test commands? No

In order to record test cases, you need to provide a command that I can use to run the tests. If your project has many test cases, enter a command that will run integration, functional, system or request tests, as opposed to unit tests. Don't worry about how long the tests will take to run, you will specify a maximum runtime in an upcoming step.

Here's a suggested test command for your project:

APPMAP=true DISABLE_SPRING=true bundle exec rails test

? Use this suggested test command? No
Here's a suggested test command for your project:

npx @appland/appmap-agent-js --recorder=process -- npm run test

? Use this suggested test command? No
? Test command (without env vars): 
? Test command (without env vars):  
? Environment variables: 
To run the tests, I will run the following command:

 

? Continue with this command? Yes
? Enter the maximum time (in seconds) to allow test cases to run (-1 to run forever): 30
Running test command:  

An error occurred: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''

Try re-running the command with the verbose flag (-v).
npm ERR! Lifecycle script `start` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @appland/appmap@3.47.0 
npm ERR!   at location: /home/test/src/appmap-js/packages/cli 
```
