### ISSUE TITLE
Installer fails when user specifies project type

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#815]
From this [log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-24T09%3A14%3A30.144Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-24T09%3A14%3A30.144Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%22b2b5fb8c063edbcb36e7056c910d1c6c73913d5cff345c9a6f02d83ca5f746e5%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog). Given the following command:
```
node_modules/.bin/appmap install -p python
```
This error is raised:
```
ReferenceError: name is not defined
at resolveSelectedInstallers (node_modules/@appland/appmap/built/cmds/agentInstaller/projectConfiguration.js:26:164)
at getProjects (node_modules/@appland/appmap/built/cmds/agentInstaller/projectConfiguration.js:168:11)
at async _handler (node_modules/@appland/appmap/built/cmds/agentInstaller/install-agent.js:127:26)
at async Object.handler (node_modules/@appland/appmap/built/cmds/agentInstaller/install-agent.js:222:35)
````

**Comment by apotterri** [comment]
This fails because `python` isn't a legal project type. We should show an error message saying that.
