### ISSUE TITLE
Indexer crashes >> cli.js index --watch --appmap-dir . exited with code 1

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#850]
I think this means the indexer crashed.

A similar error for the scanner means the scanner crashed.

```
Error: /node /home/test/.vscode-server/data/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js index --watch exited with code 1
at ChildProcess.<anonymous> (/src/services/processWatcher.ts:117:28)
at Object.onceWrapper (node:events:646:26)
at ChildProcess.emit (node:events:538:35)
at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Sample link: https://applanding.slack.com/archives/C02DU9210Q2/p1668430156678709

**Comment by symwell** [comment]
Similar error but exits after SIGKILL signal. Perhaps OOM and killed by the kernel?
```
Error: /node /home/test/.vscode-server/data/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js index --watch exited with signal SIGKILL
	at ChildProcess.<anonymous> (/out/extension.js:25658:36)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

https://applanding.slack.com/archives/C02DU9210Q2/p1668388453940059

**Comment by brikelly** [comment]
@symwell do we know if this kind of crash is user-visible? Or is it something that happens in the background inside VS Code and the user wouldn't notice (other than they're indexes not getting created, of course)?

**Comment by symwell** [comment]
I don't know.

**Comment by symwell** [comment]
dustinbyrne says

There's a log in `Output` -> `AppMap: Services` but it's otherwise not visible to the user

**Comment by symwell** [comment]
Got it to crash locally.

```
TODO: AppMap removed: /home/test/src/sample_app_6th_ed/tmp/appmap/minitest/Users_signup_valid_signup_information_with_account_activation.appmap.json
                   85
<--- Last few GCs --->

[3481588:0x547e020]  1022128 ms: Scavenge 2026.3 (2077.5) -> 2021.6 (2078.2) MB, 6.3 / 0.0 ms  (average mu = 0.610, current mu = 0.302) allocation failure; 
[3481588:0x547e020]  1022159 ms: Scavenge 2027.4 (2078.2) -> 2023.4 (2080.2) MB, 6.9 / 0.0 ms  (average mu = 0.610, current mu = 0.302) allocation failure; 
[3481588:0x547e020]  1022558 ms: Scavenge 2029.3 (2080.2) -> 2025.0 (2097.5) MB, 376.7 / 0.0 ms  (average mu = 0.610, current mu = 0.302) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb6e260 node::Abort() [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 2: 0xa7cdea  [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 3: 0xd45f00 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 4: 0xd462a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 5: 0xf235b5  [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 6: 0xf35a9d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 7: 0xf1019e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 8: 0xf11567 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
 9: 0xef1ab0 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
10: 0xee9524 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
11: 0xeeb7d8 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
12: 0x11c73ad v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
13: 0x12d62dd v8::internal::Runtime_StringCharCodeAt(int, unsigned long*, v8::internal::Isolate*) [/home/test/.nvm/versions/node/v18.8.0/bin/node]
14: 0x16e78b9  [/home/test/.nvm/versions/node/v18.8.0/bin/node]
```
I was running
```
~/src/sample_app_6th_ed$ rm tmp/appmap/minitest/*;  APPMAP=true DISABLE_SPRING=true bundle exec rails test
```
I don't see a pattern to make the crash repeatable.

**Comment by symwell** [comment]
Reproduced.

```
# in one terminal start the indexer
packages/cli$ yarn start index --watch --appmap-dir ~/src/sample_app_6th_ed/tmp/appmap/minitest

# in another terminal keep creating and deleted appmaps
 rm tmp/appmap/minitest/*; APPMAP=true DISABLE_SPRING=true bundle exec rails test; sleep 60; rm tmp/appmap/minitest/*; APPMAP=true DISABLE_SPRING=true bundle exec rails test; sleep 60; rm tmp/appmap/minitest/*; APPMAP=true DISABLE_SPRING=true bundle exec rails test; sleep 60; rm tmp/appmap/minitest/*; APPMAP=true DISABLE_SPRING=true bundle exec rails test;
 
 # in a third terminal start the scanner, then press ctrl-c to stop it, then start it again; do this "a few times" (2-3 times)
yarn build && yarn run scanner scan --watch --appmap-dir ~/src/sample_app_6th_ed/tmp/appmap
```

It crashes the indexer.  Haven't found a smaller, more accurate test to reproduce.

**Comment by kgilpin** [comment]
The first thing I would check is that the indexer uses a single queue
across all the create/update events. It's probably running a separate queue
for each event and so with many create/update events, it can eventually run
out of memory with all that AppMap data concurrently loaded.

**Comment by kgilpin** [comment]
Same thing for the scanner.

**Comment by dustinbyrne** [comment]
Regarding `exit code 1` we now have data on why this is occurring: https://github.com/getappmap/appmap-js/issues/881 and https://github.com/getappmap/appmap-js/issues/880.

If there's another issue not captured by this ticket (especially if it's not `exit code 1`) please open another ticket.

I'm going to close this for now given this ticket has been broken up into smaller issues.

**Comment by symwell** [comment]
@dustinbyrne Note this ticket also reports a "JavaScript heap out of memory" error. https://github.com/getappmap/appmap-js/issues/881, which is an error for too many open files, doesn't seem to be the same error as OOM.
