### ISSUE TITLE
Indexer exits with Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#894]
Tracking as a separate issue this error first described in https://github.com/getappmap/appmap-js/issues/881.

```
Error: ENOSPC: System limit for number of file watchers reached, watch 'venv/lib/python3.10/site-packages/plotly/validators/isosurface/lighting/__pycache__'
at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
at Object.watch (node:fs:2251:34)
at createFsWatchInstance (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:119:15)
at setFsWatchListener (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:166:15)
at NodeFsHandler._watchWithNodeFs (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:331:14)
at NodeFsHandler._handleDir (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:567:19)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async NodeFsHandler._addToNodeFs (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:617:16)
Emitted 'error' event on FSWatcher instance at:
at FSWatcher._handleError (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/index.js:647:10)
at NodeFsHandler._addToNodeFs (/home/user/.config/Code/User/globalStorage/appland.appmap/node_modules/chokidar/lib/nodefs-handler.js:645:18)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5) {
errno: -28,
syscall: 'watch',
code: 'ENOSPC',
path: 'venv/lib/python3.10/site-packages/plotly/validators/isosurface/lighting/__pycache__',
filename: 'venv/lib/python3.10/site-packages/plotly/validators/isosurface/lighting/__pycache__'
}
```

I was able to reproduce it as described [here](https://github.com/getappmap/appmap-js/issues/881#issuecomment-1339943761). This occurs from watching too many files and a limit in the kernel. This limit can't be changed without root privileges.
- On Darwin maybe `kern.num_files: 7506`
- On Linux `fs.inotify.max_user_watches = 65536`

**Comment by symwell** [comment]
Note the file watched was `lighting/__pycache__`.  Should probably add `__pycache__` in the list of ignored files.

**Comment by symwell** [comment]
Got the same error with the scanner
```
$ yarn run scanner scan --watch --appmap-dir ~/tmp/too_many_open_files
Using scanner configuration file /home/test/src/appmap-js/packages/scanner/built/sampleConfig/default.yml
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/test/tmp/too_many_open_files/requests3/1670264573_5802293_http_www_example_com_password_resets.appmap.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:637:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/test/src/appmap-js/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:645:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/test/tmp/too_many_open_files/requests3/1670264573_5802293_http_www_example_com_password_resets.appmap.json',
  filename: '/home/test/tmp/too_many_open_files/requests3/1670264573_5802293_http_www_example_com_password_resets.appmap.json'
}

Node.js v18.8.0
```
